---
- name: Test 1
  hosts: all
  remote_user: root

  tasks:
    - name: Install httpd
      ansible.builtin.apt:
        name: apache2
    - name: Create homepage
      ansible.builtin.copy:
        content: "# Hello World !"
        dest: /var/www/html/index.html
    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: apache2
        state: restarted
