---
- name: Test 1
  hosts: all
  remote_user: root

  tasks:
    - name: Install httpd
      ansible.builtin.apt:
        name: apache2
        update_cache: true

    - name: Create homepage
      ansible.builtin.copy:
        content: "# Hello World !"
        dest: /var/www/html/index.html

    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: apache2
        state: started

    - name: Check that you can connect (GET) to a page and it returns a status 200
      # connection: local
      ansible.builtin.uri:
        url: http://localhost
