---
- name: Test 1
  hosts: all
  remote_user: root

  tasks:
  - name: Install vim
    ansible.builtin.apt:
      name: vim
  - name: Get stats of the FS object
    ansible.builtin.file:
      path: /etx/passwd