---
- name: TP 02
  hosts: all
  remote_user: root

  tasks:
    - name: Uninstall packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
      when: "'{{ item }}' not in group_names"
      loop:
        - apache2
        - git
        - cowsay
        - nginx
        - mysql-server

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ item }}" 
        update_cache: true
      loop:
        - apache2
        - git
        - cowsay
        - nginx
        - mysql-server
      register: echo
      when: "'{{ item }}' in group_names"

    - name: Install packages specials Debian
      ansible.builtin.apt:
        name: "sl" 
        update_cache: true
      when: ansible_facts.os_family == 'Debian'

    - name: Install packages specials Ubuntu
      ansible.builtin.apt:
        name: "ufw" 
        update_cache: true
      when: ansible_facts.os_family == 'Ubuntu'

    - name: Get facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Show the previous registred variable
      ansible.builtin.debug:
        var: ansible_facts.packages
      when: "'nginx' in group_names or 'apache2' in group_names"

    - name: Debug
      ansible.builtin.debug:
        var: ansible_facts.os_family
      when: "'nginx' in group_names or 'apache2' in group_names"
