---
- name: TP 02
  hosts: all
  remote_user: root

  tasks:
    - name: Uninstall packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
      when: "'{{ item }}' not in group_names"
      loop:
        - apache2
        - git
        - cowsay
        - nginx
        - mysql-server

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ item }}" 
        update_cache: true
      loop:
        - apache2
        - git
        - cowsay
        - nginx
        - mysql-server
      register: echo
      when: "'{{ item }}' in group_names"

    - name: Show the previous registred variable
      ansible.builtin.debug:
        msg: "Hello world"
      loop: "{{ echo.results }}"

